Update transcript table to display uniprot isoform
Ensembl/ensembl-webcode pull request #788
Opened 2020-10-21 13:41 UTC by msmanoj

## Description

- Renamed the column name to `UniProt Match`
- `UniProt Match` column will no display the informs if they exist and shows the gene level links if not.
- Added external link entry to DEFAULTS.ini to `UNIPROT_ISOFORM`

TODO:
- Need to wait until the golssary term for  `UniProt Match` is added

## Views affected

http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Gene/Summary?g=ENSG00000159840;r=7:143381295-143391111

http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Gene/Matches?g=ENSG00000159840;r=7:143381295-143391111

## Related JIRA Issues (EBI developers only)

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5877

2020-10-22 15:43 UTC, ens-ap5 requested changes
Mostly looks good, but I don't think you need the URL template twice in DEFAULTS.ini - that's one big long list that needs tidying up! (SwissProt and TREMBL shouldn't be in there twice either). If you scroll to line 428 you'll see a heading 'RETIRE?' - when I reorganised the list several years ago, I moved everything I knew was in use out of this section, but didn't spot the duplicate values.

2020-10-22 18:11 UTC, ens-st3 commented
Table looks good. Let's wait until OLS is updated to confirm how the gene summary line should be worded and what data it should show

2020-11-23 14:06 UTC, ens-ap5 approved these changes

2020-11-23 18:35 UTC, ens-st3 approved these changes

2020-11-24 11:08 UTC, merged