Update eQTL displays to use new eQTL catalog REST endpoints rather than e! REST
Ensembl/ensembl-webcode pull request #794
Opened 2020-11-10 14:58 UTC by msmanoj

## Description
We are decommissioning the eQTL endpoints available under Ensembl REST and start to use the GTEX data added to eQTL catalog REST endpoint.

**eQTL catalog REST endpoint docs:**
http://www.ebi.ac.uk/eqtl/api-docs/

**Here is a document with details about the current and the new endpoint:**
https://docs.google.com/document/d/1FbxgKPGjQNdiP7l04btwDpC8M-u5sXLMYj96dmGn1B0/edit#heading=h.qqrby2wpp9yw

## Views affected

**Regulation Manhattan Plot**
http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Gene/Regulation?g=ENSG00000139618;r=13:32315086-32400268

**Gene expression correlations table**
http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Variation/Mappings?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179

## Related JIRA Issues (EBI developers only)

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5483
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5282
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5893
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-415

2020-11-10 15:58 UTC, ens-ap5 requested changes
For consistency, the new REST URL should go into the same plugin as the main REST URL - note that the core SiteDefs contains a placeholder URL for REST. I think that it should go into public-plugins/ensembl, but you'd need to check.

2020-11-11 09:34 UTC, msmanoj commented
> For consistency, the new REST URL should go into the same plugin as the main REST URL - note that the core SiteDefs contains a placeholder URL for REST. I think that it should go into public-plugins/ensembl, but you'd need to check.

@ens-ap5  - Unlike REST URL, the eQTL REST url will always be the same across all sites so I'm wondering if it is worth having just a placeholder in the core SiteDefs and overriding in all other places.
I also noticed a similar entry where we have not used a placeholder:
https://github.com/Ensembl/ensembl-webcode/blob/2686b6197ed670e4b5aa29ba48719ff872b34070/conf/SiteDefs.pm#L233

2020-11-11 09:42 UTC, ens-ap5 commented
Do we even have eQTL data outside www? If not, I see no point in having it in the main SiteDefs and then overriding it elsewhere.

2020-11-11 09:49 UTC, msmanoj commented
> Do we even have eQTL data outside www? If not, I see no point in having it in the main SiteDefs and then overriding it elsewhere.

No, we don't. Do we need to define it somewhere else so that it is specific to www?

2020-11-11 09:51 UTC, ens-st3 commented
We have it for grch37, archives, and externally maintained mirrors

2020-11-11 20:02 UTC, ens-st3 commented on modules/EnsEMBL/Web/ImageConfig/generegview.pm
> +  warn "gtex_tissue_example: ". $gtex_tissue_example;
remove warn

2020-11-23 18:41 UTC, ens-st3 commented
Gene Regulation page - can you remove 'ARRAY(0x37766098) GTEX eQTLs' from the list of available tracks.
Gene expression correlations - I'm afraid all I can see is 'undefined'
![Screenshot 2020-11-23 at 18 40 47](https://user-images.githubusercontent.com/6160390/100001701-6dd8ef80-2dbb-11eb-9c43-ebfcea0c6170.png)
![Screenshot 2020-11-23 at 18 40 28](https://user-images.githubusercontent.com/6160390/100001705-70d3e000-2dbb-11eb-8960-13fde0d134f4.png)

2020-11-24 09:40 UTC, msmanoj commented
> Gene Regulation page - can you remove 'ARRAY(0x37766098) GTEX eQTLs' from the list of available tracks.
@ens-st3  - That's done.
> Gene expression correlations - I'm afraid all I can see is 'undefined'
- I think this is just a caching issue. Could you please try again by clearing your cache?

2020-11-26 12:44 UTC, merged