Parse use_vcf_consequences from json file
Ensembl/ensembl-webcode pull request #905
Opened 2022-08-02 08:49 UTC by likhitha-surapaneni

Description

This PR aims to parse a flag `use_vcf_consequences` from the json file which allows the user to fetch consequences from the VCF file instead of the database.

Requires: https://github.com/Ensembl/ensembl-variation/pull/830

2022-08-02 09:45 UTC, ens-ap5 requested changes
I'm not sure that's the right place to put it, as it will override the limiting by slice size on line 197, which could break the track on large slices. Would be better to put it just before line 196, with an appropriate if block.

2022-08-10 08:12 UTC, likhitha-surapaneni commented
Hi @ens-ap5 , thank you for the review.

The intention is to override the limiting the slice size on line 197 if and only if `use_vcf_consequences` is defined in the JSON file. This way, when `use_vcf_consequences` is defined, it fetches consequences for all slice ranges and not just < 1e5. If it is not defined, then the original behaviour is restored. Kindly let me know if this makes sense in terms of memory utilised.

2022-08-16 14:30 UTC, ens-ap5 commented
Hi Likhitha, have you tested this on your sandbox on slices > 1e5? That would be the real test of whether this approach works.

2022-08-25 12:13 UTC, likhitha-surapaneni commented
Hi @ens-ap5 , I tested this on sandbox with and without the flag and it seems to work as expected for slices > 1e5

2022-08-25 12:37 UTC, ens-ap5 approved these changes
OK, let's go with this and see what happens!

2022-08-25 12:38 UTC, ens-ap5 commented
One final thought - is this flag defined in any other species? Putting it onto release/107 means it will eventually get pushed out to all the current sites, not just rapid release

2022-08-30 12:55 UTC, likhitha-surapaneni commented
Hi @ens-ap5 , the flag is not defined in any other species i.e all other species are unaffected by the code changes.

2022-09-06 10:24 UTC, merged